### ISSUE TITLE
predict function error

### ISSUE THREAD

**Issue by raysunau** [raysunau/pydatoolkit#1]
ERROR - Error while preparing predictions: Number of features of the model must match the input. Model n_features is 12 and input n_features is 13 
Traceback (most recent call last):
  File "/Users/rsun/projects/code/pydatoolkit/datk/model.py", line 480, in predict
    y_pred = model.predict(x_val)
  File "/Users/rsun/projects/py_venv/pydatk/lib/python3.7/site-packages/sklearn/ensemble/_forest.py", line 629, in predict
    proba = self.predict_proba(X)
  File "/Users/rsun/projects/py_venv/pydatk/lib/python3.7/site-packages/sklearn/ensemble/_forest.py", line 673, in predict_proba
    X = self._validate_X_predict(X)
  File "/Users/rsun/projects/py_venv/pydatk/lib/python3.7/site-packages/sklearn/ensemble/_forest.py", line 421, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "/Users/rsun/projects/py_venv/pydatk/lib/python3.7/site-packages/sklearn/tree/_classes.py", line 399, in _validate_X_predict
    % (self.n_features_, n_features))
ValueError: Number of features of the model must match the input. Model n_features is 12 and input n_features is 13

**Comment by raysunau** [comment]
Test data has the target column, fix the error by removing it.
